### ISSUE TITLE
Patterns allowing for zero length matches fail for zero length haystacks

### ISSUE THREAD

**Issue by BlazingTwist** [mnemnion/mvzr#5]
Expected behaviour: this test should not fail.
```zig
test "zero length match on zero length haystack" {
    const mvzr = @import("mvzr.zig");
    const regex = mvzr.compile(".*");
    const match = regex.?.match("");
    try std.testing.expect(match != null);
    try std.testing.expectEqual(0, match.?.start);
    try std.testing.expectEqual(0, match.?.end);
}
```

Actual behaviour: the test fails.
Removing this line *seems* to not break the code and fixes the issue.
https://github.com/mnemnion/mvzr/blob/c130207a3f6913a7eb1c542f9bbe8b7e274224e0/src/mvzr.zig#L115

However, I have not checked if this breaks any assumptions made in `matchInternal`.

**Comment by mnemnion** [comment]
A situation I had not contemplated it would seem.   It does look like simply removing the spurious check solves the issue.

Fixed in `v0.3.2`, thanks for the report.
